package.json, src/components/App.js, src/components/FileInputContainer.js, src/components/FileInputRow.js, src/components/__stories__/App.stories.js, src/components/__stories__/FileInputRow.stories.js, src/components/__tests__/__snapshots__/Storyshots.test.js.snap
Instead of having to setup a server and all that json endpoint stuff, sometimes you just want to statically show one stats file, say after a deploy. Then on the next deploy rebuild the whole thing.
This adds a new env var called `REACT_APP_STATS_URL` which lets you bake-in a url where the stats file can be found, and it'll be fetched on page load.
The simplest way to use this env var is with a relative path and something like [`serve`](https://github.com/zeit/serve). It can be as easy as:
```bash
REACT_APP_STATS_URL=./stats.json npm run build
webpack --json $project_dir > build/stats.json
server build
```
Using REACT_APP_STATS_URL lets you go ahead and move the whole `build/` folder someplace else, tag it with the commit id, archive it, etc.
=> Bake in stats file at build time

index.md
When attempting to build Bonsai locally, a step in the [Running Bonsai](https://pinterest.github.io/bonsai/#running-bonsai) section of the GH pages indicates that users should install `serve` via the command: `yarn install -g serve`. A recent version of yarn changes how packages should be installed. I received this error message: `error `install` has been replaced with `add` to add new dependencies. Run "yarn global add serve" instead.`
The docs should indicate that users install `serve` via this command: `yarn global add serve`
=> indicating new yarn install instructions

src/components/FileInputContainer.js
This is a PR to quickly give people feedback when they're uploading invalid json files. See #19 for examples of how that can happen.
With so many plugins and things that can live inside a webpack.config.js file I expect there's lots of potential for non-json files to be produced.
=> Trap json parse errors and throw up an alert when it fails.

src/components/stats/SelectedChunk.js
Because chunks could be called `0`.
=> Check against null, instead of truthiness to show ChunkBreadcrumb

src/actions.js, src/components/stats/ModuleTable.js, src/components/stats/ModuleTableContainer.js, src/components/stats/SelectedChunk.js, src/reducer.js
This moves the sort & filter click handlers and data into the redux store with actions. This centralizes the data and makes it easier to change/listen to data from multiple modules.
=> Create sort & filter actions and use them

src/components/stats/ModulePanels.js
This should make it much more readable because it'll always be about the same width as the first column, or less.
=> Switch to using module.name in the dependants&imports dropdowns

.travis.yml
We already test against node version8 with the `- node` line, but this calls it out before we hit v9
=> Explicitly test node version8 in travis ci

package.json
These folders are already in the .gitignore list, but it's nice if everything that can be built can also be removed in dev.
=> Clean built artifacts in the docs folder

src/UrlStateEncoder.js, src/components/stats/BlacklistTable.js, src/components/stats/ChunkDropdown.js, src/index.js, src/reducer.js, src/stats/getParentChunks.js, src/stats/splitUnreachableModules.js, src/types/Stats.js
Using the new redux actions and the store we can easily change state from any where in the app. So I've added a new module that serializes the picked modules into the current uri, and deserializes it on startup. This makes it possible to share views when the selected url is available (so when a server is used and provides a file from the network).
Addresses #41
=> Serialize picked file/chunk/removed-modules in url hash.

package.json, src/actions.js, src/components/App.js, src/components/AppContainer.js, src/fetchJSON.js, src/index.js, yarn.lock
This will prevent double-loading of the same files from the server whenever the dropdown is clicked, and also stop multiple requests from firing when the hash-url is used to pre-load a file.
=> Simplify file loading, and cache all json responses.

src/components/__tests__/__snapshots__/Storyshots.test.js.snap, src/components/stats/formatModuleName.js
They didn't affect display because there was no following content, so lets rip them out.
=> Stop printing extra <br/> tags at the end of formatModuleName

src/scrollToAndFocus.js
This adds an `isWithinViewport` check to the existing behavior so we don't get scrolled around when we don't need to be.
=> `scrollToAndFocus` only scrolls when target is not in viewport

src/stats/__tests__/splitUnreachableModules.test.js, src/stats/splitUnreachableModules.js
Previously it was possible to exhaust the call stack with recursive calls to recordChildModules. Now we use an array to track the reachable moduleIds and then map them back to the module object at the end.
=> Use and iterative approach and add tests to splitUnreachableModules

src/stats/__tests__/getCollapsableParentOf.test.js, src/stats/getCollapsableParentOf.js, src/utils/reducer.js
Fixing #173 
That object lookup in `reducer.js` was going bad when I had weird things in the url bar I think. So we can move it inside `getCollapsableParentOf` and check it each time we recurse.
=> Fix possibility of null object in `getCollapsableParentOf` and add tests

.storybook/config.js, package.json, yarn.lock
The storybook channels were throwing in the console because there were different version of some addons installed, apparently yarn/greenkeeper were not locking versions the right way for storybook. I'll have to watch out for that better in the future.
Also, followed the redux instructions for HMR and got the storybook config doing the right thing for our <Provider>
=> Fix storybook channel setup and redux HMR

.codecov.yml
Also renamed the project groups here.
=> codecov patches will skip looking at component coverage

src/cli/fileSystemHelper.js, src/components/Bootstrap/DropdownList.js, src/components/FileSelectors.js, src/components/FileSelectorsContainer.js, src/components/JsonFilePicker.js, src/components/__stories__/FileSelectors.stories.js, src/components/__tests__/__snapshots__/Storyshots.test.js.snap, src/components/stats/ChunkDropdown.js, src/stats/chunkSizes.js, src/types/__tests__/getRawStats.test.js, src/types/getRawStats.js, src/utils/__tests__/reducer.test.js, src/utils/actions.js, src/utils/reducer.js
This resolves an issue where multi-config stats files were not parsed
properly if they were loaded from a pre-configured server endpoint.
=> Refactor multi-config logic into a new picker to support multi-config stats files.

.travis.yml, package.json, src/__test_helpers__/shims.js, src/components/Bootstrap/Button.js, src/components/Bootstrap/Dropdown.js, src/components/Navbar.js, src/components/OffsetPageAnchor.js, src/components/Unit.js, src/components/__stories__/Unit.stories.js, src/components/__tests__/OffsetPageAnchor.test.js, src/components/__tests__/__snapshots__/Storyshots.test.js.snap, src/components/stats/BlacklistTable.js, src/components/stats/BlacklistTableBody.js, src/components/stats/ChunkDropdown.js, src/components/stats/ModuleTable.js, src/components/stats/ModuleTableBody.css, src/components/stats/ModuleTableBody.js, src/components/stats/ModuleTableHead.js, src/components/stats/formatModuleName.js, src/types/__tests__/getRawStats.test.js, src/types/getRawStats.js, src/utils/__tests__/withTimings.test.js, src/utils/reducer.js, src/utils/withTimings.js, yarn.lock
Render optimizations to reduce extra dom nodes, remove too many document listeners, download glyphicons earlier, and remove the uploaded source from the redux store.
=> Smattering of render optimizations

src/components/FileSelectors.js, src/components/stats/ChunkBreadcrumb.js, src/components/stats/ChunkDropdown.js, src/components/stats/__stories__/ChunkBreadcrumb.stories.js, src/stats/__tests__/__snapshots__/getEntryHierarchy.test.js.snap, src/stats/__tests__/getEntryHierarchy.test.js, src/stats/__tests__/getParentChunks.test.js, src/stats/chunkSizes.js, src/stats/fullModuleData.js, src/stats/getChunkModules.js, src/stats/getEntryHierarchy.js, src/stats/getParentChunks.js
There was a recursive error were would would iterate through cyclic modules references and lockup the window before crashing. This uses an iterative approach to assign references to the existing objects, instead of building a new tree of objects and assigning references forever. 
Also fix spelling
=> Fix recursion problem in getEntryHierarchy

.babelrc.cli, .flowconfig, .travis.yml, package.json, scripts/build-webpack-examples.sh, scripts/template-webpack-build-common.js, src/cli.js, src/cli/main.js, yarn.lock
This fixes the package.json commands to run the cli & also the webpack examples. 
We can now run the cli in 'dev mode' with `yarn start:cli`, this compiles the files on the fly, so it's slower to run, but it's one step.
Also, we've got `yarn build:cli` for production mode. This shoots the files out to `./bin`which package.json points to.
Finally we've fixed the args for the webpack-examples stats build, seems like some are broken here, and in the upstream too. :(. See `examples/commonjs`.
=> Build commands for CLI & webpack-examples

package.json, yarn.lock
We can replace this baked-in dependency with calls to `npm flow-typed` when it's needed.
=> Remove flow-typed dependency

package.json
Stomp some warnings about deprecated field names from flow-coverage-report
Warnings removed from cli:
```
WARN: "includeGlob" config file property has been renamed to "globIncludePatterns"
WARN: "excludeGlob" config file property has been renamed to "globExcludePatterns"
WARN: "type" config file property has been renamed to "reportTypes"
```
=> Update flow-coverage-report config field names
