src/components/FileInputContainer.js, src/components/FileInputRow.js, src/components/JsonFilePicker.js, src/components/__stories__/FileInputRow.stories.js, src/components/__tests__/__snapshots__/Storyshots.test.js.snap, src/fetchJSON.js
this also extracts out the fetchJSON method, and puts the this.loadURL() call in the right place
=> Nicer looking file upload area

src/components/FileInputContainer.js, src/fetchJSON.js, src/stats/getChunkModules.js, src/types/Stats.js, src/types/shapeGuard.js
We should check the shape of the stats file, just a little bit, before starting to extract data from it. This can help us find some simple problems and surface them quickly, separate from the innards of the stats/ folder.
=> Check the shape of the uploaded stats file

src/components/stats/FilterDisplay.js, src/components/stats/FilterModuleNameForm.js, src/components/stats/ModuleTableHead.js
This tweaks out the filter buttons a little to make them look more clickable, gives things title attributes as basic explainers, and I touched up the width of the module name text area.
=> Add icons, title attrs and try to make filter buttons look more like buttons

src/components/Navbar.js
make the tagline regular size text instead of title.
=> Tweak navbar text

src/components/stats/LoopTable.js, src/components/stats/SelectedChunk.js, src/stats/getExtendedModulesById.js, src/types/Stats.js
An affordance to identify and break big circular dependency chains as needed
See #34
=> Create a new section to list curcular dependencies

.travis.yml
Lets try to set up the lockfile stuff per https://github.com/greenkeeperio/greenkeeper-lockfile
=> Setup greenkeeper-lockfile

.flowconfig, package.json, public/index.html, public/manifest.json, src/index.js, src/registerServiceWorker.js
Following the steps from cra:
https://github.com/facebookincubator/create-react-app/blob/master/CHANGELOG.md#100-may-18-2017
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app
=> Add an app manifest & service worker

dev-server/api/index.json, package.json, yarn.lock
Use serve to have a mock api that returns some stats files. This is an example of how you could use REACT_APP_API_LIST_ENDPOINT, and is also a quick way to setup a server to test that env var during development.
The two stats files were just pulled from the latest gh-pages update. It's not lovely that they're part of the repo, but they're not too huge that I'm worried about size.
=> Add a yarn command to spin up a dev server with an api backend.

package.json, src/actions.js, src/components/App.js, src/components/AppContainer.js, src/components/FileInputContainer.js, src/components/__stories__/App.stories.js, src/fetchJSON.js, src/index.js, src/reducer.js, yarn.lock
This pulls out the file loading/pick functions to the to level <App /> and index.js files (and helpers). It introduces an initial set of redux actions to track the currently picked file, files we know about and show in the dropdown, and also the history of loaded file data for quick comparisons.
=> Introduce Redux with some file load/pick actions

docs/analyzing.md, docs/build-options.md, docs/index.md, docs/manual-analysis.md, docs/stats-files.md
Because I'm an idiot and didn't port over the updated docs.
reapply of 60ca85001f163c7a61d762bf6b826dd74628a531
=> Reapply the changes from #46

docs/index.md
=> Fix link in docs.

src/actions.js, src/components/SelectedChunkContainer.js, src/components/__stories__/App.stories.js, src/components/stats/SelectedChunk.js, src/reducer.js, src/setupTests.js
This makes it possible to manage the selected chunks and includes/ignored modules from outside that component.
=> Let the SelectedChunkContainer use the redux store and actions.

.travis.yml, package.json
=> run all builds as test steps and use NODE_ENV=production for the cli

.storybook/config.js, src/__test_helpers__/defaults.js, src/components/Bootstrap/Panel.js, src/components/Bootstrap/__stories__/Panel.stories.js, src/components/__stories__/App.stories.js, src/components/__tests__/__snapshots__/Storyshots.test.js.snap, src/components/stats/BlacklistTable.js, src/components/stats/BlacklistTableContainer.js, src/components/stats/LoopTable.js, src/components/stats/LoopTableContainer.js, src/components/stats/ModuleDataContainer.js, src/components/stats/SelectedChunk.js, src/components/stats/__stories__/BlacklistTable.stories.js
This cleans things up and hoists the bootstrap row elements into the SelectedChunk element which will make layout and additions simpler to reason about. Also, i've added a Panel helper so I don't have to remember the panel-body rules and when to use it.
=> Extract some page sections into their own container components.

src/components/__tests__/__snapshots__/Storyshots.test.js.snap, src/components/stats/BlacklistTable.js, src/components/stats/BlacklistTableBody.js, src/components/stats/ModuleTableBody.js, src/components/stats/ModuleTableHead.js, src/index.css
Following basic table formatting guidelines.
=> Align numeric columns to the right

src/components/Bootstrap/Button.js, src/components/__tests__/__snapshots__/Storyshots.test.js.snap, src/components/stats/ToggleExpandModeButton.js, src/components/stats/__stories__/ToggleExpandModeButton.stories.js
Less border, full width, looks good
=> Fix 'unique imports' button styling

src/components/Bootstrap/Dropdown.js, src/components/Bootstrap/__stories__/Dropdown.stories.js, src/components/__tests__/__snapshots__/Storyshots.test.js.snap
Setting this to true will open the dropdown by default.
=> Add a defaultIsOpen prop to <Dropdown>

src/components/Navbar.js
We want to clear out that kind of state so things can load completely.
=> Reset the url hash when we click to reload the page

package.json
=> chore(package): update @storybook/addon-storyshots to version 3.4.0

package.json
=> chore(package): update @storybook/addon-actions to version 3.4.0

package.json
=> chore(package): update @storybook/react to version 3.4.0

.travis.yml
This matches the src/__test_helpers__/*-config.js files as well
=> Update webpack.config file location to fix auto-deploy

src/__test_helpers__/shims.js, src/index.js, src/setupTests.js, src/shims.js
The index.js needs to use the globals, not test files.
=> Split shims into test-only and global files.

package.json
=> chore(package): update eslint to version 6.2.2
